version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - ci
  - package-ecosystem: "npm"
    directory: "/tests/qcurl"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - tests
  - package-ecosystem: "pip"
    directory: "/tests/libcurl_consistency"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - tests
