# SPDX-License-Identifier: MIT
# 同时用于 package() 暂存树和最终 Arch 包的解包树，不产生新的清单文件。
cmake_minimum_required(VERSION 3.19)

foreach(argument IN ITEMS PACKAGE_ROOT PACKAGE_VERSION SOURCE_ROOT)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing argument: ${argument}")
    endif()
endforeach()

function(require_file relative)
    if(NOT EXISTS "${PACKAGE_ROOT}/${relative}" OR IS_DIRECTORY "${PACKAGE_ROOT}/${relative}")
        message(FATAL_ERROR "Required package file is missing: ${relative}")
    endif()
endfunction()

function(check_shared_library name)
    set(library "usr/lib/lib${name}.so.${PACKAGE_VERSION}")
    require_file("${library}")
    foreach(suffix IN ITEMS ".2" "")
        set(link "${PACKAGE_ROOT}/usr/lib/lib${name}.so${suffix}")
        if(NOT IS_SYMLINK "${link}")
            message(FATAL_ERROR "Missing library symlink: ${link}")
        endif()
        file(READ_SYMLINK "${link}" target)
        if(suffix STREQUAL ".2")
            set(expected_target "lib${name}.so.${PACKAGE_VERSION}")
        else()
            set(expected_target "lib${name}.so.2")
        endif()
        if(NOT target STREQUAL expected_target)
            message(FATAL_ERROR "Unexpected library symlink: ${link} -> ${target}")
        endif()
    endforeach()
    find_program(READELF readelf REQUIRED)
    execute_process(COMMAND "${READELF}" -d "${PACKAGE_ROOT}/${library}"
        RESULT_VARIABLE result OUTPUT_VARIABLE dynamic ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT dynamic MATCHES "\\(SONAME\\).*\\[lib${name}\\.so\\.2\\]")
        message(FATAL_ERROR "Invalid SONAME in ${library}: ${error}")
    endif()
    if(dynamic MATCHES "\\((RPATH|RUNPATH)\\)")
        message(FATAL_ERROR "Unexpected RPATH/RUNPATH in ${library}")
    endif()
endfunction()

function(check_test_support_library)
    set(library "usr/lib/libQCurlTestSupport.a")
    require_file("${library}")
    find_program(NM nm REQUIRED)
    execute_process(COMMAND "${NM}" -g --defined-only "${PACKAGE_ROOT}/${library}"
        RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT symbols MATCHES " [TW] " OR symbols MATCHES "__gnu_lto_slim")
        message(FATAL_ERROR "TestSupport archive has no usable native code: ${error}")
    endif()
endfunction()

function(public_headers output)
    require_file("usr/include/qcurl/QCurlConfig.h")
    file(READ "${PACKAGE_ROOT}/usr/include/qcurl/QCurlConfig.h" config)
    file(READ "${SOURCE_ROOT}/tests/public_api/surface_manifest.json" surface)
    string(JSON count LENGTH "${surface}" headers)
    math(EXPR last "${count} - 1")
    set(headers "usr/include/qcurl/QCurlConfig.h")
    foreach(index RANGE ${last})
        string(JSON path GET "${surface}" headers ${index} path)
        string(JSON visibility GET "${surface}" headers ${index} visibility)
        string(JSON installed GET "${surface}" headers ${index} currentInstall)
        if(NOT visibility STREQUAL "Public" OR installed STREQUAL "none")
            continue()
        endif()
        if(path MATCHES "^QCWebSocket" AND NOT config MATCHES "\n#define QCURL_WEBSOCKET_SUPPORT(\n| )")
            continue()
        endif()
        list(APPEND headers "usr/include/qcurl/${path}")
    endforeach()
    set(${output} "${headers}" PARENT_SCOPE)
endfunction()

function(check_metadata relative)
    file(READ "${PACKAGE_ROOT}/${relative}" content)
    foreach(root IN ITEMS SOURCE_ROOT BUILD_ROOT)
        if(DEFINED ${root} AND NOT "${${root}}" STREQUAL "")
            string(FIND "${content}" "${${root}}" offset)
            if(NOT offset EQUAL -1)
                message(FATAL_ERROR "Producer path leaked into ${relative}: ${${root}}")
            endif()
        endif()
    endforeach()
    if(relative STREQUAL "usr/lib/cmake/QCurl/QCurlTargets.cmake"
       AND content MATCHES "CURL::libcurl|ZLIB::ZLIB|QCurl::libcurl_shared")
        message(FATAL_ERROR "Private dependency leaked into shared Core interface")
    endif()
endfunction()

public_headers(expected)
foreach(name IN ITEMS QCurl QCurlOtherExtras)
    check_shared_library("${name}")
    list(APPEND expected "usr/lib/lib${name}.so.${PACKAGE_VERSION}"
        "usr/lib/lib${name}.so.2" "usr/lib/lib${name}.so")
endforeach()
check_test_support_library()
list(APPEND expected "usr/lib/libQCurlTestSupport.a")
foreach(name IN ITEMS QCurlConfig QCurlConfigVersion QCurlTargets QCurlTargets-release
        QCurlBlockingExtrasTargets QCurlOtherExtrasTargets QCurlOtherExtrasTargets-release
        QCurlTestSupportTargets QCurlTestSupportTargets-release)
    list(APPEND expected "usr/lib/cmake/QCurl/${name}.cmake")
endforeach()
list(APPEND expected "usr/lib/pkgconfig/qcurl.pc" "usr/lib/pkgconfig/qcurl-other-extras.pc"
    "usr/share/licenses/qcurl/LICENSE" "usr/share/licenses/qcurl/THIRD_PARTY_NOTICES.md")

foreach(relative IN LISTS expected)
    require_file("${relative}")
    if(relative MATCHES "\\.(cmake|pc)$")
        check_metadata("${relative}")
    endif()
endforeach()
foreach(name IN ITEMS LICENSE THIRD_PARTY_NOTICES.md)
    file(READ "${SOURCE_ROOT}/${name}" original)
    file(READ "${PACKAGE_ROOT}/usr/share/licenses/qcurl/${name}" installed)
    if(NOT original STREQUAL installed)
        message(FATAL_ERROR "License text differs from source: ${name}")
    endif()
endforeach()

# Arch 元数据只在最终包中出现；其他文件必须全部属于当前安装面。
list(APPEND expected .PKGINFO .BUILDINFO .MTREE)
file(GLOB_RECURSE actual LIST_DIRECTORIES FALSE RELATIVE "${PACKAGE_ROOT}" "${PACKAGE_ROOT}/*")
foreach(relative IN LISTS actual)
    if(NOT relative IN_LIST expected)
        message(FATAL_ERROR "Forbidden package file: ${relative}")
    endif()
endforeach()
list(LENGTH actual count)
message(STATUS "QCurl Arch package contents: PASS (${count} files)")
