#!/usr/bin/env python3
"""Generate a Doxygen INPUT fragment from QCurl's public surface manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

NON_PUBLIC_INSTALL_VALUES = {"internal", "private", "not-installed", "none"}


def _load_manifest(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"failed to parse manifest {path}: {exc}") from exc


def _is_release_api_header(entry: dict[str, Any]) -> bool:
    current_install = str(entry.get("currentInstall", "")).strip().lower()
    layer = str(entry.get("layer", "")).strip().lower()
    header = str(entry.get("path", "")).strip()
    if not header:
        return False
    if current_install in NON_PUBLIC_INSTALL_VALUES:
        return False
    if layer == "internal":
        return False
    if header.endswith("_p.h") or "/private/" in header or header.startswith("private/"):
        return False
    return True


def _collect_headers(manifest: dict[str, Any], source_dir: Path) -> list[Path]:
    headers: list[Path] = []
    seen: set[str] = set()
    for entry in manifest.get("headers", []):
        if not isinstance(entry, dict) or not _is_release_api_header(entry):
            continue
        header = str(entry["path"]).strip()
        if header in seen:
            raise SystemExit(f"duplicate manifest header: {header}")
        seen.add(header)
        path = source_dir / header
        if not path.is_file():
            raise SystemExit(f"manifest header does not exist: {path.as_posix()}")
        headers.append(path)
    if not headers:
        raise SystemExit("manifest did not yield any public API headers")
    return headers


def _validate_headers(headers: list[Path]) -> None:
    invalid = [
        path.as_posix()
        for path in headers
        if path.name.endswith("_p.h") or "private" in path.parts
    ]
    if invalid:
        raise SystemExit("internal/private headers in Doxygen input:\n" + "\n".join(invalid))


def _render_fragment(headers: list[Path], manifest_path: Path) -> str:
    input_value = " ".join(path.as_posix() for path in headers)
    return (
        "# Generated by scripts/generate_doxygen_input_from_surface_manifest.py\n"
        f"# Source manifest: {manifest_path.as_posix()}\n"
        "# Do not edit by hand; update tests/public_api/surface_manifest.json instead.\n"
        f"INPUT = {input_value}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=Path("tests/public_api/surface_manifest.json"))
    parser.add_argument("--source-dir", type=Path, default=Path("src"))
    parser.add_argument("--output", type=Path, default=Path("build/doxygen/qcurl_api_input.doxy"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the generated input and report the selected headers",
    )
    args = parser.parse_args(argv)

    manifest = _load_manifest(args.manifest)
    headers = _collect_headers(manifest, args.source_dir)
    _validate_headers(headers)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(_render_fragment(headers, args.manifest), encoding="utf-8")

    if args.check:
        print(f"[doxygen-input] wrote {args.output.as_posix()} with {len(headers)} public headers")
        for header in headers:
            print(header.as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
