# First-party Qt targets must not depend on keyword macros (signals/slots/emit).
function(qcurl_enable_qt_no_keywords _qcurl_target)
    if(NOT TARGET "${_qcurl_target}")
        message(FATAL_ERROR "Cannot enable QT_NO_KEYWORDS on unknown target: ${_qcurl_target}")
    endif()
    get_target_property(_qcurl_type "${_qcurl_target}" TYPE)
    if(_qcurl_type STREQUAL "INTERFACE_LIBRARY")
        target_compile_definitions("${_qcurl_target}" INTERFACE QT_NO_KEYWORDS)
    else()
        target_compile_definitions("${_qcurl_target}" PRIVATE QT_NO_KEYWORDS)
    endif()
endfunction()

function(qcurl_verify_first_party_targets_have_qt_no_keywords)
    set(_qcurl_missing)
    _qcurl_verify_directory("${CMAKE_SOURCE_DIR}" _qcurl_missing)
    get_property(_qcurl_consumer_dirs GLOBAL PROPERTY QCURL_STANDALONE_CONSUMER_SOURCE_DIRS)
    foreach(_qcurl_consumer_dir IN LISTS _qcurl_consumer_dirs)
        file(READ "${_qcurl_consumer_dir}/CMakeLists.txt" _qcurl_consumer_cmake)
        if(NOT _qcurl_consumer_cmake MATCHES
           "add_compile_definitions[ \t\r\n]*\\([ \t\r\n]*QT_NO_KEYWORDS[ \t\r\n]*\\)")
            list(APPEND _qcurl_missing "standalone consumer (${_qcurl_consumer_dir})")
        endif()
    endforeach()
    if(_qcurl_missing)
        string(JOIN "\n  " _qcurl_missing_text ${_qcurl_missing})
        message(FATAL_ERROR
            "First-party target(s) missing QT_NO_KEYWORDS compile definition:\n  ${_qcurl_missing_text}")
    endif()
endfunction()

function(_qcurl_verify_directory _qcurl_dir _qcurl_missing_var)
    if(_qcurl_dir MATCHES "/curl(/|$)" OR _qcurl_dir MATCHES "/node_modules(/|$)")
        return()
    endif()
    get_property(_qcurl_targets DIRECTORY "${_qcurl_dir}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_qcurl_target IN LISTS _qcurl_targets)
        get_target_property(_qcurl_imported "${_qcurl_target}" IMPORTED)
        if(_qcurl_imported)
            continue()
        endif()
        get_target_property(_qcurl_type "${_qcurl_target}" TYPE)
        if(NOT _qcurl_type MATCHES
           "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY|INTERFACE_LIBRARY)$")
            continue()
        endif()
        get_target_property(_qcurl_defs "${_qcurl_target}" COMPILE_DEFINITIONS)
        get_target_property(_qcurl_iface_defs "${_qcurl_target}" INTERFACE_COMPILE_DEFINITIONS)
        if(NOT "QT_NO_KEYWORDS" IN_LIST _qcurl_defs
           AND NOT "QT_NO_KEYWORDS" IN_LIST _qcurl_iface_defs)
            list(APPEND ${_qcurl_missing_var} "${_qcurl_target} (${_qcurl_dir})")
        endif()
    endforeach()
    get_property(_qcurl_children DIRECTORY "${_qcurl_dir}" PROPERTY SUBDIRECTORIES)
    foreach(_qcurl_child IN LISTS _qcurl_children)
        _qcurl_verify_directory("${_qcurl_child}" ${_qcurl_missing_var})
    endforeach()
    set(${_qcurl_missing_var} "${${_qcurl_missing_var}}" PARENT_SCOPE)
endfunction()
